### ISSUE TITLE
Tweak ticket-recognizing regexes.

### ISSUE THREAD

**Issue by toddlmiller** [JoshKarpel/chtc-bot#11]
The test

> GT0x1000 

causes the bot to respond with ticket 0.  This can't be right.  (We shouldn't support hex, but it's still probably wrong.)  The problem is

> Do you remember that one ticket?  (GT#1000?)

which should probably work -- we can't require whitespace.

Not sure if we should explicitly allow leading and trailing parentheses as well as other punctuation, or maybe forbid alphabetical characters after the pound.

**Comment by matyasselmeci** [comment]
Can you strip leading 0s as well? Don't want people to use octal in this day and age :-)

**Comment by toddlmiller** [comment]
It looks like `re.compile(r"rt#([1-9]\d*)(?: |[^AZaz]|$)", re.I)` (and
`re.compile(r"gt#([1-9]\d*)(?: |[^AZaz]|$)", re.I)`) will do the trick.  Seems easy to lose in a merge, though, so unless #26 takes forever, wait for it to be done.

**Comment by JoshKarpel** [comment]
#26 is done!

**Comment by toddlmiller** [comment]
I'm a little iffy on mutating the test text.  It may be more idiomatic to declare some constants and mutate those in the parameterization (also, PyTest, why do you spell parameterize wrong?); this may lead to better error messages.

**Comment by toddlmiller** [comment]
If Josh thinks the test should be changed, he can open another ticket. ;)
