### ISSUE TITLE
FRQ: Link against chtc-bot's own tickets

### ISSUE THREAD

**Issue by toddlmiller** [JoshKarpel/chtc-bot#12]
I'm thinking

> We should talk about bot#12

and maybe we could then easily extend the code to add another prefix for other GitHub projects of interest.

**Comment by JoshKarpel** [comment]
Maybe implement as a generic `GitHubTicketLinker(repo = "JoshKarpel/chtc-bot", prefix = "bot")` for said future-proofing?
