### ISSUE TITLE
Connect to CHTC staff schedule page

### ISSUE THREAD

**Issue by JoshKarpel** [JoshKarpel/chtc-bot#13]
Per Ian, it'd be cool if the bot could read the CHTC staff schedule page and spit out that information on request.

**Comment by toddlmiller** [comment]
Suggestion:

> Is karpel in today?

or

> chtcbot, is karpel in today?

and

> chtcbot, who's in today?

**Comment by GregThain** [comment]
One thing we want to be very careful of is not spamming slack, and trying to keep the signal to noise ratio high.

So, I think it would be better to post the schedule once per day, early in the day, as the posting the answer to anyone's question in a group slack channel is equivalent to shouting it down the hall at everyone.

**Comment by toddlmiller** [comment]
Agreed.  However, since the point of the bot is that I frequently forget or delete the relevant email, I'd like to keep the ability to ask the bot directly and have it reply directly (that is, not on the channel).

**Comment by toddlmiller** [comment]
While developing the web-scraping part of this command, I added a little try/except block around `current_app.config["..."]` so that I could just set the password in the environment, instead.  This seemed inappropriate to commit, so I removed it and went looking for a way to create required app context.

After some fumbling, it seemed like the easiest way to do that -- and to solve the problem of intercepting the call `web.slack.post_message()` -- was to run my little script under pytest.  Fine.  But putting the password configuration in `base.py` broke the tests when run by github, because the password wasn't in the environment.  Not fine.

What's the right way to do this?  Maybe some sort of command-line option to pytest?  (Add this file to the configuration?)

**Comment by JoshKarpel** [comment]
I recommend separating the "get the schedule page" code into a separate function so that you can just feed `get_users_by_status` with a copy of the HTML in the test suite, like we do for the other scrapers. Then the code the needs the secret is never invoked in the test suite, but you can still run the methods in a test script by setting them in your own environment manually.

We should probably have a new environment, `config/dev.py` for running locally. It should basically do the same thing as `heroku.py`, but with `.get` instead of `[]` so that the environment variables are optional unless you need them.

**Comment by toddlmiller** [comment]
Obviously, for the test suite, feeding in a fixed HTML blob is the right way to go.  For some reason that didn't seem like a good idea when doing live development, although I guess I could have had the fetch function take the password as an argument and worked around the problem that way.

Speaking of -- we have two dev files lying around already: `./dev.py` and `./set-dev-env.sh`.  I'm not quite sure what the intended use for either of them is.

`./dev.py` seems misnamed -- it's identical to wsgi.py except for using the "testing" config.  I'm not sure what it's intended use is -- I'm not presently sure why you would want to spin up the Flask app locally -- but it seems like -- if convention permits, that `wsgi-testing.py` might be a better name.  Then `wsgi-dev.py` could load the development environment.

`./set-dev-env.sh` seems to be intended for use with `./dev.py`, but it's not clear how... maybe something having to do with the canonical way to invoke Flask?  (I'm not sure why putting stuff in your environment is a better way to go than a script which sets up the proper environment and then invokes Flask, but maybe there's a lot of Flask to invoke.)

**Comment by JoshKarpel** [comment]
Hmmm. I'm not entirely sure what I was going for with those either. I must have used them for something at some point, but now I'm not sure. Will poke back through commits when I get a chance and try to figure out what I was going for.

Could you clarify what your "live development" workflow looked like?

**Comment by toddlmiller** [comment]
I'm not longer sure I wasn't just confusing myself trying to do things the (unknown to me) "right way", but basically I have a little helper script I've been using to check various functions:

`#!/home/tlmiller/miniconda3/bin/python

import bs4
from web import http
from web import commands
from web.commands.scrapers import hard_shorten

# response = http.cached_get_url(knobs.KNOBS_URL)
# soup = bs4.BeautifulSoup(response.text, "html.parser")
# description = knobs.get_knob_description(soup, "DEFRAG_NAME")
# print(f"{description}\n")

# response = http.cached_get_url(jobads.ATTRS_URL)
# soup = bs4.BeautifulSoup(response.text, "html.parser")
# # description = jobads.get_attrs_description(soup, "ACCtGROup")
# description = jobads.get_attrs_description(soup, "DAGManNodesMask")
# print(f"{description}\n")

sch = commands.SubmitsCommandHandler(rescrape_timeout=300)
response = http.cached_get_url(sch.url)
soup = bs4.BeautifulSoup(response.text, "html.parser")

description = sch.get_description(soup, "queue")
# print(repr(description))
print(hard_shorten(description[0], 512))
`

And this is slower to run, but less troublesome to write than picking a good example from the relevant webpage and copying and pasting it and writing the pytest bits.  (I mean, that all has to happen, but a little script like this can help pick a good example, too.)  So clearly to test if the fetching of the schedule information is working, I should do pretty much the same thing for it, right?

And that's where the ScheduleCommandHandler wanting an application context comes in (followed by catching the RuntimeError and pulling the secret out of the environment, instead).

**Comment by toddlmiller** [comment]
TODO:
1.  Write tests
2.  Fix problem where the 'bot can't reply to the specific user who requested the summary.
3.  Consider GregT's suggestion.

**Comment by toddlmiller** [comment]
1. Next up.
2. Fixed by a8daf4b.
3. Considered; we'll announce the command as-is and see what people actually want.
