### ISSUE TITLE
Get descriptions of HTCondor config knobs

### ISSUE THREAD

**Issue by JoshKarpel** [JoshKarpel/chtc-bot#14]
i.e., search https://htcondor.readthedocs.io/en/latest/admin-manual/configuration-macros.html for a given name and print out the corresponding description block.

Not sure what the command should be... `knob#CONDOR_HOST`? Maybe it should be a slash command? `/knobs CONDOR_HOST COLLECTOR_HOST ...`

**Comment by toddlmiller** [comment]
I like `/knob[s] KNOB KNOB_KNOB`, but I wonder if there should be one command for "tell me what that knob is" and another one for "answer a question by pointing at the manual".

Maybe even `chtcbot, tell {#channel|@here|@user-in-DM} about KNOB`?
