### ISSUE TITLE
Preserve formatting in knobs

### ISSUE THREAD

**Issue by JoshKarpel** [JoshKarpel/chtc-bot#16]
Since #14 we have a slash command to get HTCondor config knobs, but the text comes back completely un-formatted. In particular, it clobbers `fixed text` and links, both of which are annoying.

Since we don't need to parse all possible HTML (just a small subset to turn back into markdown), I think we can get away with a reasonably simple https://docs.python.org/3/library/html.parser.html .

There are also occasional special characters that sneak in (see `COLLECTOR_HOST`, which has a ` (â:â)` in it right now), and things like tables. Perhaps we can do something about those as well...

**Comment by toddlmiller** [comment]
The /submits command does some formatting that the other two scrapers don't, but once that's fixed, I'm thinking the new truncation code renders this issue mostly moot.

**Comment by toddlmiller** [comment]
Added list and paragraph formatting to the other two scrapers.
