### ISSUE TITLE
FRQ: add /submits command

### ISSUE THREAD

**Issue by toddlmiller** [JoshKarpel/chtc-bot#23]
which would do what /knobs does, but for submit keywords, which we should be able to fish out of 

https://htcondor.readthedocs.io/en/latest/man-pages/condor_submit.html

**Comment by toddlmiller** [comment]
The second part of the commit message for 7391a06 should have been for #22.

**Comment by toddlmiller** [comment]
So the thread window is narrow enough that even if we adjusted the hard-wrap to usually fit, the second and subsequent answers would be hard to tread.  We could print the first entry and if there are more, a link to the web page; we could print the first entry with a button that sends the rest as DMs; or we could give the bot a channel to be verbose in, and a print a link to that if there are multiple entries.  Another option might be to publicly reply with the first entry and DM the original requester the remainder, although that might devolve back into the second option pretty quickly.

For multiple replies, I guess we could also just ask the original requester which one to dump back to the channel.  (Truncate the individual replies to four lines or so, print them all with a button that says 'this one!' that just duplicates the (hidden) whole reply into the channel.)  This wouldn't really for long replies, though.

**Comment by JoshKarpel** [comment]
I think a link makes the most sense. The important thing is not really that the information literally shows up in Slack (although that's nice when it happens), but that we "find" the information for the requester. The first few lines followed by a direct link to the right submit option is good enough for me.

**Comment by toddlmiller** [comment]
OK, I'm declaring victory.
