### ISSUE TITLE
Add functional test for /knobs and /jobads

### ISSUE THREAD

**Issue by toddlmiller** [JoshKarpel/chtc-bot#25]
The unit tests are fine, but frequently miss problems.  Add another test to each one's test suite which combines all of the unit test cases by calling get_*_descrption().

More end-to-end testing will have to wait for mocks, probably.

**Comment by JoshKarpel** [comment]
I'll take a crack at this, and try to do some mocking besides. I'm also frustrated with how easy it is to break the slash commands.
